[options]
admin_passwd = postgres
db_host = db
db_user = postgres
db_password = postgres
db_port = 5432
addons_path = /mnt/extra-addons
proxy_mode = True
data_dir = /var/lib/odoo

[options]
admin_passwd = admin
db_host = db
db_user = postgres
db_password = postgres
db_port = 5432
addons_path = /mnt/extra-addons
proxy_mode = True
data_dir = /var/lib/odoo
